#!/bin/sh

# Copy this file to .git/hooks/pre-commit.

GITHUB_REPO=$(\
    git remote -v \
    | grep fetch \
    | grep origin \
    | awk '{print $2}' \
    | sed 's/git@/http:\/\//' \
    | sed 's/com:/com\//' \
    | sed 's/\.git//')


GITBOOK_URL=$(cat gitbook-url)


cat << EOF >  docs/documentation-metadata.md
This file is created at commit-time on a git repo that has this hook installed.

Commits may be made by Gitbook or by authorized documentation authors without this hook,
so this may or may not be the most recent commit date:

### Commit Time

* **Local Time:** $(date)
* **UTC Time:**   $(date -u)

### Links

* **Github URL:** [$GITHUB_REPO]($GITHUB_REPO)
* **Gitbook URL:** [$GITBOOK_URL($GITBOOK_URL)

EOF

git add docs/documentation-metadata.md
