#!/bin/sh

cat << EOF >  docs/timestamp.md
This is the most recent commit made
on a git repo with this pre-commit hook. Commits may be made
by Gitbook or by authorized documentation authors
without this hook, so this may or may not
be the most recent commit:

$(PAGER= git log -1)

$(date -u) 

Github URL: $(git remote -v | grep origin | head -1)

Gitbook URL: $(cat gitbook-url)

EOF

git add docs/timestamp.md
