#!/bin/sh

# Copy this file to .git/hooks/pre-commit.

GITHUB_REPO=$(\
    git remote -v \
    | grep fetch \
    | grep origin \
    | awk '{print $2}' \
    | sed 's/git@/http:\/\//' \
    | sed 's/com:/com\//' \
    | sed 's/\.git//')


GITBOOK_URL=$(cat gitbook-url)


cat << EOF >  docs/documentation-metadata.md
# Documentation Metadata

This page is created at commit-time when the git repo committed to has this pre-commit hook installed.

If a commit has been made on a repo not having this hook installed, then this page
will not accurately reflect the most recent commit.


### Commit Time

* **Local Time:** $(date)
* **UTC Time:**   $(date -u)

### Links

* **Github URL:** [$GITHUB_REPO]($GITHUB_REPO)
* **Gitbook URL:** [$GITBOOK_URL]($GITBOOK_URL)

EOF

git add docs/documentation-metadata.md
